### ISSUE TITLE
报错Application Rustdesk Api Sever V2 cannot handle your request

### ISSUE THREAD

**Issue by yunxilyf** [GMYXDS/rustdesk-api-server#2]
我这运行老提示这个错误，数据库密码用户名都是对的，也报错连接失败
Application Rustdesk Api Sever V2 cannot handle your request
```
[2023-07-04 21:14:49 -0400] [423] [ERROR] Exception occurred while handling uri: 'http://IP:21114/api/reg?username=yunxi&password=yunxi&auth_key=123456'
Traceback (most recent call last):
File "handle_request", line 97, in handle_request
from sanic_ext.extensions.base import Extension # type:      #####ignore
File "/www/wwwroot/rustdesk-api-server-main/server_v2.py", line 326, in api_reg
check_nums = await app.ctx.poolmysqlasync.check_num_rows('rustdesk_v2.rustdesk_users','username',username)
File "/www/wwwroot/rustdesk-api-server-main/mysql_async.py", line 81, in check_num_rows
res = await self.fetchone(sql, value)
File "/www/wwwroot/rustdesk-api-server-main/mysql_async.py", line 53, in fetchone
await self.init_pool()
File "/www/wwwroot/rustdesk-api-server-main/mysql_async.py", line 33, in init_pool
PoolMysqlAsync.pool = await aiomysql.create_pool(**self.db_args)
File "/www/server/pyporject_evn/44fe74ad09101138b974b41ea45df115_venv/lib/python3.10/site-packages/aiomysql/pool.py", line 29, in _create_pool
await pool._fill_free_pool(False)
File "/www/server/pyporject_evn/44fe74ad09101138b974b41ea45df115_venv/lib/python3.10/site-packages/aiomysql/pool.py", line 182, in _fill_free_pool
conn = await connect(echo=self._echo, loop=self._loop,
File "/www/server/pyporject_evn/44fe74ad09101138b974b41ea45df115_venv/lib/python3.10/site-packages/aiomysql/connection.py", line 75, in _connect
await conn._connect()
File "/www/server/pyporject_evn/44fe74ad09101138b974b41ea45df115_venv/lib/python3.10/site-packages/aiomysql/connection.py", line 540, in _connect
await self._request_authentication()
File "/www/server/pyporject_evn/44fe74ad09101138b974b41ea45df115_venv/lib/python3.10/site-packages/aiomysql/connection.py", line 844, in _request_authentication
auth_packet = await self._read_packet()
File "/www/server/pyporject_evn/44fe74ad09101138b974b41ea45df115_venv/lib/python3.10/site-packages/aiomysql/connection.py", line 652, in _read_packet
packet.raise_for_error()
File "/www/server/pyporject_evn/44fe74ad09101138b974b41ea45df115_venv/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
err.raise_mysql_exception(self._data)
File "/www/server/pyporject_evn/44fe74ad09101138b974b41ea45df115_venv/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'yuncheng'@'localhost' (using password: YES)")
[2023-07-04 21:14:50 -0400] [421] [WARNING] Invalid HTTP request received.
[2023-07-04 21:14:50 -0400] [422] [WARNING] Invalid HTTP request received.
[2023-07-04 21:14:50 -0400] [420] [WARNING] Invalid HTTP request received.
``` #1 @GMYXDS

**Comment by GMYXDS** [comment]
你的数据是不是外部不能连接
pymysql.err.OperationalError: (1045, "Access denied for user 'yuncheng'@'localhost' (using password: YES)")
明显是数据库错误，自己排查，百度
看是不是权限问题啥的
尝试把数据库ip改成你服务器的ip，或者0.0.0.0 或则localhost

**Comment by yunxilyf** [comment]
> 

啥意思，是不能用本地数据库吗

**Comment by yunxilyf** [comment]
> 

那个IP就是服务器IP

**Comment by GMYXDS** [comment]
你用navicat这些软件可以连上吗

**Comment by yunxilyf** [comment]
> 你用navicat这些软件可以连上吗

可以

**Comment by GMYXDS** [comment]
你mysql 分配的yuncheng 权限是所有主机都能连接吗，是不是yuncheng@%

**Comment by yunxilyf** [comment]
本地都可以连接的

**Comment by yunxilyf** [comment]
部署在同一个服务器上

**Comment by GMYXDS** [comment]
不应该啊，你邮箱联系我一下，我帮你看看gmyxds132@163.com
